[IV-23-24] Objetivo 1
josemponce/RutaMusical pull request #2
Opened 2023-09-28 09:18 UTC by josemponce

* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-29 11:29 UTC, danieeeld2 commented
Voy a ayudarte con la revisión😄. Mientras leo,me he fijado que se te ha pasado colocarle la etiqueta de user-stories a las HUs. Si tienes problema para crearla etiquetame, pero es bastante sencillo😊

2023-09-29 11:35 UTC, manuelvico0102 requested changes
La parte de los milestone lo veo correcto

2023-09-29 11:35 UTC, manuelvico0102 commented on docs/historias.md
> + - Juanmi es el director de la banda de música de Albolote y tiene que planificar una serie de conciertos por distintos pueblos para conseguir dinero para financiar la agrupación musical y le gustarí
Las historias de usuario son utilizadas para poder empezar con la modelización del problema, por lo que te aconsejo añadir más contexto. Ya que con las historias de usuario ya se debería entender todo el problema como que datos se van a utilizar.

2023-09-29 11:44 UTC, danieeeld2 commented on docs/historias.md
> + - Juanmi es el director de la banda de música de Albolote y tiene que planificar una serie de conciertos por distintos pueblos para conseguir dinero para financiar la agrupación musical y le gustarí
Siguiendo un poco con lo que comenta @manuelvico0102, tal vez sería buena idea especificar a qué se refiere con la ruta en la que los músicos podrían estar disponibles. Leyendo un poco la descripción que tienes en el README.md, entiendo que, al trabajar con festividades de pueblos, esta anotación se podría referir a las fechas de dichas festividades o a la distancia que se encuentran estos pueblos. En todo caso creo que es buena idea especificarlo

2023-09-29 12:05 UTC, josemponce commented
Gracias por tu comentario @javigp2002,

Que te parece si para ello añadiera la figura del tesorero y así poder dividir en el **[HU1] director** de la banda que sólo quiere saber los pueblos disponibles de forma que encuentre los suficentes como para crear una ruta y por otro lado el **[HU2] tesorero** que es el que quiere maximizar la ganancia y necesitaría encontrar la ruta óptima, de forma que a cada uno podría asiganarle un milestone distinto.

2023-09-29 12:20 UTC, josemponce commented on docs/historias.md
> + - Juanmi es el director de la banda de música de Albolote y tiene que planificar una serie de conciertos por distintos pueblos para conseguir dinero para financiar la agrupación musical y le gustarí
Gracias por vuestros comentarios,

He actualizado las historias de usuarios teniendo en cuenta vuestros consejos, añadiendo más contexto y explicando mejor ciertos puntos.

2023-09-29 12:23 UTC, javigp2002 approved these changes
:+1: Están bien los cambios, espero que los demás revisores lo aprueben también. Si necesitas algo no dudes en mencionarme :smile:.

2023-09-29 12:23 UTC, javigp2002 commented on docs/milestones.md
> + - El obejtivo será implementar una clase o modulo que pueda calcular un recorrido que máximice la posible ganancia de la agrupación musical.
Hay una errata en "objetivo".

2023-09-29 12:47 UTC, manuelvico0102 approved these changes

2023-09-30 11:24 UTC, josemponce commented
Listo para revisión @JJ.

2023-10-01 09:39 UTC, JJ approved these changes
:+1: la verdad es que @danieeeld2 @javigp2002 y @manuelvico0102 han dejado poco margen para la mejora. Podría quizás dar un poco más de contexto sobre las rutas, pero quizás eso ya se pueda hacer en la siguiente.

2023-10-01 09:39 UTC, JJ commented on docs/historias.md
> + - El tesorero busca que dicha ruta sea una que ofrezca la mayor cantidad de ganacia posible de forma que le gustaría que se seleccionasen aquellos pueblos que ofrecieran dicho beneficio óptimo.
typo; `ganacia`

2023-10-06 10:44 UTC, merged