[IV-23-24] Objetivo 3
josemponce/RutaMusical pull request #22
Opened 2023-11-21 08:35 UTC by josemponce

* [ ] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ] ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [ ] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2023-11-21 15:18 UTC, migueruiz requested changes
Hola! seré tu revisor en este PR, veo que no has dicho nada del task runner, no se si aún no lo has decidido, o algo.

2023-11-21 15:18 UTC, migueruiz commented on docs/gestor-dependencias.md
> +
Deberías de decir que criterios usas para elegir, ya que sino, podría quedar ambiguo. 😄

2023-11-22 15:51 UTC, pluque01 requested changes
A parte de lo que te ha dicho @migueruiz, hay muchos errores ortográficos. Te recomiendo usar algún tipo de herramienta que compruebe los errores ortográficos. Si usas VSCode puedes mirar extensiones como [esta](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex).

2023-11-22 15:51 UTC, pluque01 commented on docs/gestor-tareas.md
> +- `Mage`: posiblemente el más utilizado pricipalmente por estar bien integrado en el ecosistmema de Go, aunque su sistaxis pueda resultar más complicada para la gente que no esté familiarizada con Go
¿Cómo sabes que Mage es el más utilizado? Por ejemplo entre Task y Mage, se podría decir que Task es más utilizado por el número de estrellas en GitHub

2023-11-22 18:49 UTC, Christianlr commented
Hola @josemponce! Te recomendaría que le echases un ojo a los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-3.md#sobre-los-criterios-para-elegir-las-herramientas) para que así pudieras determinar buenos criterios en cuanto a la elección de las herramientas. En definitiva, basarse por facilidad, popularidad (mencionados en el gestor de tareas)... no son puntos que realmente te cubran las necesidades de tu proyecto. Principalmente, debes reducir la deuda técnica. Por lo tanto, creo que sería buena idea enfocar los criterios a otro punto más "real" y elegir aquello que realmente te ayude a resolver tu problema. Animo! :smile:

2023-11-22 18:50 UTC, Christianlr requested changes
Hola @josemponce! Te recomendaría que le echases un ojo a los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-3.md#sobre-los-criterios-para-elegir-las-herramientas) para que así pudieras determinar buenos criterios en cuanto a la elección de las herramientas. En definitiva, basarse por facilidad, popularidad (mencionados en el gestor de tareas)... no son puntos que realmente te cubran las necesidades de tu proyecto. Principalmente, debes reducir la deuda técnica. Por lo tanto, creo que sería buena idea enfocar los criterios a otro punto más "real" y elegir aquello que realmente te ayude a resolver tu problema. Animo! 😄

2023-11-24 12:10 UTC, josemponce commented on docs/gestor-tareas.md
> +- `Mage`: posiblemente el más utilizado pricipalmente por estar bien integrado en el ecosistmema de Go, aunque su sistaxis pueda resultar más complicada para la gente que no esté familiarizada con Go
Hola @pluque01, tienes razón, supuse mal el que creía que más se utilizaba por estar mejor integrado en Go, ya lo he corregido, gracias por la ayuda.

2023-11-24 12:11 UTC, josemponce commented on docs/gestor-tareas.md
> +- `Mage`: posiblemente el más utilizado pricipalmente por estar bien integrado en el ecosistmema de Go, aunque su sistaxis pueda resultar más complicada para la gente que no esté familiarizada con Go
Resuelto en commit [57c4ee4](https://github.com/josemponce/RutaMusical/pull/22/commits/57c4ee491eaecad370b5b9dcc65bd46aa7b54b37)

2023-11-24 12:12 UTC, josemponce commented on docs/gestor-dependencias.md
> +
Es que en el caso del gestor de dependencias, en el caso de Go no hay mucho margen a la discusión sobre cual usar, siendo Go Modules la principal herramienta.

2023-11-24 12:18 UTC, josemponce commented
Hola @migueruiz, @pluque01 y @Christianlr, he estado leyendo vuestros comentarios y he hecho los cambios necesarios para que espero que lo veáis correcto ahora.
He corregido los errores ortográficos y he cambiado los criterios por los cuáles he escogido el gestor de tareas a través del documento de los errores comunes.
Cuando podáis decirme si lo veis bien ahora, un saludo y muchas gracias por la ayuda.

2023-11-24 14:48 UTC, migueruiz approved these changes
Después de lo que me has comentado, creo que está bien. Suerte en la revisión!

2023-11-26 17:40 UTC, pluque01 approved these changes
Yo lo veo listo para revisión 👍

2023-11-27 16:26 UTC, Christianlr approved these changes
Lo veo bien! :+1:

2023-11-29 10:16 UTC, JJ approved these changes
:+1:
Porfa, la próxima vez pide explícitamente la revisión.

2023-12-10 19:06 UTC, merged