[IV 23-24] Objetivo 2
josemponce/RutaMusical pull request #7
Opened 2023-10-06 11:18 UTC by danieeeld2

Trabajando sobre repositorio de @josemponce.
###### Pendiente añadir lista de comprobaciones e issues cerrados (Se modificará al final a medida que se vaya realizando la práctica)

2023-10-06 11:22 UTC, josemponce commented
Perfecto @danieeeld2, lo enlazo con el Milestone 0.

2023-10-19 07:28 UTC, danieeeld2 commented
@josemponce Cuando puedas revisa los cambios, que he arreglado un par de cosas siguiendo los consejos de clase. También, te he pedido en #13 que le asignes una etiqueta y ya, por último, asigna todos los issues a M0 para que así salga completado cuando acabemos 😆.

PD: Le tienes que asignar la etiqueta también de hacktoberfest al PR.

Cuando acabes, si lo ves todo bien, ya le solicitamos revisión a JJ.

2023-10-19 08:16 UTC, danieeeld2 commented
Por cierto, que no te lo he comentado:
- En principio, los músicos son objeto-valor, ya que siempre van a tener la misma disponibilidad, nombre y tocan el mismo instrumento.
- La agrupación igual, es un objeto-valor
- Los conciertos, como la distancia va variando, ya que te acercas o te alejas, lo veo como una entidad

2023-10-19 12:16 UTC, danieeeld2 commented
Listo para revisión @JJ

2023-10-19 12:28 UTC, JJ commented
> Todo perfecto para la revisión @danieeeld2.

Por favor, aprueba explícitamente (en la pestaña files, REview) y [sigue la lista de comprobación](http://jj.github.io/IV/documentos/proyecto/2.Modelo#lista-de-comprobaci%C3%B3n-para-el-propietarioa-del-repositorio), insertándola en tal revisión.

2023-10-19 13:38 UTC, josemponce approved these changes
Listo para revisión @JJ

2023-10-19 15:37 UTC, JJ requested changes
Realmente, la metodología que se ha seguido es más o menos razonable, y para lo que se ha seguido, creo que el resultado ha sido bastante bueno; la verdad es que no se pueden poner muchas pegas.
Hay sin embargo algún problema. El principal es que has tratado con dos historias de usuario. En ingeniería siempre hay que priorizar una respecto a la otra. Las dos son diferentes, y requieren una lógica de negocio diferente. 
El segundo es que hay algunas cosas que serían resultado de la lógica de negocio, como la distancia entre conciertos, pero que estás poniendo como parte del concierto. Si lo que hay que hacer es calcular una ruta, la distancia dependerá del orden de los mismos.
Y el que no lo hayas hecho así es que creo que has dejado las decisiones implícitas en los issues que has planteado, en vez de plantear los diferentes problemas. Por ejemplo ¿cuál es el coste de una ruta que dure tres días frente a otra que dure dos días? ¿Importa la distancia o importa cuanto se tarda en llegar? ¿O esto y el coste?
En fin, creo que en general has seguido el camino correcto pero queda un poquito por recorrer.

2023-10-19 16:06 UTC, danieeeld2 commented
Muchas gracias por las aportaciones @JJ. Intentaré sacarle un poquito de tiempo luego o mañana en clase para acabar de perfeccionarlo😄. Y gracias a ti @josemponce por contestar y revisar todo tan rápido, se agradece mucho😉

2023-10-20 12:28 UTC, danieeeld2 commented
Buenas @josemponce, he replanteado el tema de la distancia en el nuevo issue #16 siguiendo los consejos de JJ. Me gustaría que revisases los cambios cuando puedas y que le coloques la etiqueta de invalido al issue #10 😉

2023-10-23 12:52 UTC, JJ requested changes
Como en la anterior iteración, creo que en general se ha hecho un buen trabajo de reflejar en el código los issues; el problema es que a veces el planteamiento de los issues o es incompleto, o al final de la resolución de los mismos podría haberse mirado qué es lo que se representa en conjunto. En parte esa es labor de @josemponce, que tendría que tomar el código y pensar ¿cómo programo yo la lógica de negocio? antes de aprobarlo. Pero en todo caso, conviene que le déis una vuelta los dos, ya estamos más cerca.

2023-10-23 12:52 UTC, JJ commented on internal/conciertos.go
> +	Duracion 		int // minutos
Cuando hay un comentario al lado de un código, o uno, o el otro, o los dos, son erróneos. ¿Qué problema hay con llamarlo DuracionMinutos?

2023-10-23 12:52 UTC, JJ commented on internal/conciertos.go
> +	Duracion 		int // minutos
Por otro lado, no hay nada en #8 que hable de la duración. ¿Qué utilidad tiene la duración en la lógica de negocio?

2023-10-23 12:52 UTC, JJ commented on internal/musicos.go
> +	Instrumento 		string
NO hay ninguna referencia en #8 al instrumento que toca el músico, ni la importancia que tiene dentro del modelo. Por otro lado, "closes xxx" como mensaje de commit no sigue las mejores prácticas. Aparte de incluir el issue, el mensaje de commit debería ayudar al revisor a saber qué es lo que se ha hecho y por qué.

2023-10-25 11:44 UTC, danieeeld2 commented on internal/conciertos.go
> +	Duracion 		int // minutos
En #8 solo discutía con @josemponce si la ganancia viene dada directamente por el dinero o si tiene mas factores y ya al decidir que depende de varios factores, pensamos en añadirlo en #9 . La idea viene de #4 donde dicen que los músicos les gustaría no trabajar demasiado.

2023-10-25 11:47 UTC, danieeeld2 commented on internal/musicos.go
> +	Instrumento 		string
Es cierto que el instrumento no aporta nada a la lógica de negocio de dentro de la asignatura, lo añadí después de hablar con @josemponce en persona y ver el Milestone3 (que no entra dentro de la asignatura), donde planifica el día de cada músico y pues, entiendo pj, que no todos los trompetas pueden estar descansando a la vez ya que sino no hay trompetas tocando en ese momento. Si quiere lo quito porque es verdad que no viene a cuento para la lógica de negocio principal ni se extrae directamente de ninguna HU.

2023-10-25 11:52 UTC, danieeeld2 commented on internal/musicos.go
> +	Instrumento 		string
En cuanto a los commits @JJ, yo los estoy haciendo como `commit -m "closes xxx" -m "avanza xxx" -m "breve explicación de lo que se ha hecho`. Al hacerlo así sale como si fuera en cascada y hay que darle a los 3 puntos para desglosarlo. No sé si se refiere a eso o que la explicación del commit debería ser más extensa.

2023-10-25 12:42 UTC, JJ commented on internal/musicos.go
> +	Instrumento 		string
Para que la persona que revisa entienda qué se está haciendo, es mejor que la breve explicación esté en la primera línea, que es la que aparece en `blame` o la historia del fichero. Así no tiene, uno por uno, que ir a la explicación en cascada.

2023-10-25 12:43 UTC, JJ commented on internal/musicos.go
> +	Instrumento 		string
> Es cierto que el instrumento no aporta nada a la lógica de negocio de dentro de la asignatura, lo añadí después de hablar con @josemponce en persona y ver el Milestone3 (que no entra dentro de la asignatura), donde planifica el día de cada músico y pues, entiendo pj, que no todos los trompetas pueden estar descansando a la vez ya que sino no hay trompetas tocando en ese momento. Si quiere lo quito porque es verdad que no viene a cuento para la lógica de negocio principal ni se extrae directamente de ninguna HU.

En general se debe trabajar solo para alcanzar el producto mínimo del siguiente milestone, siguiendo la HU vigente en cada momento. No se trata de lo que yo quiera o no, mi labor aquí es ver las HUs e issues y ver de qué forma el código aporta valor a los que se esté trabajando en cada momento.

2023-10-25 12:44 UTC, JJ commented on internal/conciertos.go
> +	Duracion 		int // minutos
Tanto el anterior como este tienen que ser una solución al problema que se plantee en el issue correspondiente. Si ahora lo refleja mejor, tendrás que explicar por qué lo hace.

2023-10-25 12:45 UTC, danieeeld2 commented on internal/musicos.go
> +	Instrumento 		string
Okay, entiendo. Lo suyo sería invertir el orden como usted dice. Lo tendré en cuenta de ahora en adelante😄

2023-10-25 12:47 UTC, danieeeld2 commented on internal/musicos.go
> +	Instrumento 		string
> > Es cierto que el instrumento no aporta nada a la lógica de negocio de dentro de la asignatura, lo añadí después de hablar con @josemponce en persona y ver el Milestone3 (que no entra dentro de la asignatura), donde planifica el día de cada músico y pues, entiendo pj, que no todos los trompetas pueden estar descansando a la vez ya que sino no hay trompetas tocando en ese momento. Si quiere lo quito porque es verdad que no viene a cuento para la lógica de negocio principal ni se extrae directamente de ninguna HU.
> 
> En general se debe trabajar solo para alcanzar el producto mínimo del siguiente milestone, siguiendo la HU vigente en cada momento. No se trata de lo que yo quiera o no, mi labor aquí es ver las HUs e issues y ver de qué forma el código aporta valor a los que se esté trabajando en cada momento.

Okay, lo tendré en cuenta también ahora al corregir los errores.

2023-10-25 12:48 UTC, danieeeld2 commented on internal/conciertos.go
> +	Duracion 		int // minutos
> Tanto el anterior como este tienen que ser una solución al problema que se plantee en el issue correspondiente. Si ahora lo refleja mejor, tendrás que explicar por qué lo hace.

Okay, muchas gracias. Ahora cuando coma me pongo a perfilar el objetivo, a ver si a la tercera ya es la buena 🤣😄

2023-10-25 12:52 UTC, JJ commented on internal/conciertos.go
> +	Duracion 		int // minutos
Ánimo

2023-10-25 15:35 UTC, danieeeld2 commented on internal/musicos.go
> +	Instrumento 		string
Resuelto en 686fe4680434a6850da4d57bb04888d972a695f8

2023-10-25 15:36 UTC, danieeeld2 commented
@JJ ¿Le pido revisión primero a @josemponce y ya cuando él lo vea te pido la revisión, no?

2023-10-25 15:51 UTC, JJ commented
> @JJ ¿Le pido revisión primero a @josemponce y ya cuando él lo vea te pido la revisión, no?

Si, por favor. Que pase también la lista de comprobación de nuevo.

2023-10-25 19:28 UTC, josemponce approved these changes
He revisado la lista de comprobación y lo veo todo correcto. 
Listo para revisión @JJ

2023-10-26 07:46 UTC, JJ commented
> He revisado la lista de comprobación y lo veo todo correcto.
> Listo para revisión @JJ

Hubiera preferido que la copiaras explícitamente. En fin, vamos a ello.

2023-10-26 07:47 UTC, JJ approved these changes
👍

2023-10-26 07:47 UTC, JJ commented on internal/conciertos.go
> +	DuracionMinutos	int
¿Hay un unsigned int?

2023-10-26 07:55 UTC, danieeeld2 commented on internal/conciertos.go
> +	DuracionMinutos	int
Resuelto en bd784b331a034d1ee6363cb2963a5e1a29ea3a53

2023-11-20 17:11 UTC, merged